{
 "title": "Rucio Internal Services",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "bin",
    "query": "5m,30m,1h,2h,6h,12h,1d,2d,3d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Core Rucio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[Transfer Submission] Percentage Success over $bin",
   "type": "gauge",
   "description": "Submissions from Rucio to FTS with the last non-zero value. This is a metric of submissions submitted to FTS not FTS job success. This being anything other than 100% points to issues between Rucio and FTS, or issues with FTS.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "[Transfer Submission] Percentage Failure over $bin",
   "type": "gauge",
   "description": "Submissions from Rucio to FTS with the last non-zero value. This is a metric of submissions submitted to FTS not FTS job success. This being anything other than 100% points to issues between Rucio and FTS, or issues with FTS.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "[Transfer Submission] Success and Failure over $bin",
   "type": "timeseries",
   "description": "Submissions from Rucio to FTS with the last non-zero value. This is a metric of submissions submitted to FTS not FTS job success.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(state) (increase(rucio_transfertool_fts3_submission_total{state=\"success\"}[$bin]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by(state) (increase(rucio_transfertool_fts3_submission_total{state=\"failure\"}[$bin]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "[Core] Rule Update per minute over $bin",
   "type": "bargauge",
   "description": "Rule Status. Either submitted to FTS or in a state of DONE or waiting in Rucio for the next heartbeat.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (increase(rucio_core_request_get_next_requests_total[$bin]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files Transferred over $bin",
   "type": "stat",
   "description": "Number of transfers performed",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (increase(rucio_transfertool_fts3_submission_total{state=\"success\"}[$bin]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files Deleted over $bin",
   "type": "stat",
   "description": "Number of deletions performed",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (increase(rucio_daemons_reaper_reaper_delete_count[$bin]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Transfer Submission] Failed submissions to FTS over $bin",
   "type": "timeseries",
   "description": "Failed job submissions from Rucio to FTS",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "round(sum by(state) (increase(rucio_transfertool_fts3_submission_total{state=\"failure\"}[$bin])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Transfer Submission] Logarithmic successful submissions to FTS over $bin",
   "type": "timeseries",
   "description": "Successful job submissions from Rucio to FTS",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "round(sum by(state) (increase(rucio_transfertool_fts3_submission_total{state=\"success\"}[$bin])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Daemons] Daemon actions per second over $bin",
   "type": "timeseries",
   "description": "The number of requests to the server from users or workflow mechanisms per second over the bin period.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(rucio_daemons_conveyor_finisher_handle_requests_total[$bin]))",
     "legendFormat": "Conveyor Finisher"
    },
    {
     "expr": "sum(rate(rucio_daemons_conveyor_poller_update_request_state_total[$bin]))",
     "legendFormat": "Conveyor Poller"
    },
    {
     "expr": "sum(rate(rucio_daemons_conveyor_submitter_get_transfers_total_transfers_total[$bin]))",
     "legendFormat": "Conveyor Submitter"
    }
   ]
  },
  {
   "title": "[Core] Requests to Server over $bin",
   "type": "timeseries",
   "description": "The number of requests to the server from users or workflow mechanisms per second over the bin period.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(rucio_core_request_get_and_mark_next_count[$bin]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Transmogrifier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "[Transmogrifier]  Transmogrifier Jobs created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(rucio_daemons_transmogrifier_transmogrifier_addnewrule_done_total[$bin]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "[Transmogrifier] Maximum Transmogrifier Job time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(rucio_daemons_transmogrifier_transmogrifier_job_duration_bucket[$bin]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Reaper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "[Reaper] Deletion at RSEs over $bin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(rse) (increase(rucio_daemons_reaper_reaper_delete_sum[$bin]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Undertaker] Delete DIDs over $bin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(rucio_daemons_undertaker_undertaker_undertaker_delete_dids_total[$bin]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}